name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Show working directory info
      run: pwd && ls

    - name: Setup environment variables
      run: |
        echo "$(pwd)/bin" >> $GITHUB_PATH
        echo "GOPATH=$(pwd)" >> $GITHUB_ENV
        
    - name: Build
      run: bash ./build.sh
      
    - name: Install test dependencies
      run: bash ./install-test.sh

    - name: Test
      run: bash ./run-test.sh
